### ISSUE TITLE
Sample rate values

### ISSUE THREAD

**Issue by SLS8** [adafruit/Adafruit_CircuitPython_LSM6DS#30]
Hello
While waiting for the LSM6DSOX to arrive I was looking on the code from _Rate.add_values()_ the Hz values used are: 1.6, 12.5, 26, 52, 104, 208, 416, 833, 1066, 3033, 6066
But in the page 11 of the datasheet the last three values are different: 1666, 3332, 6664
Why are 1066, 3033 and 6066 used in the code?
Thanks

**Comment by siddacious** [comment]
It looks like the table you referenced is listing "typical" values; the values in the library are derived from the values specified for the register that controls the data rate (`CTRL1_XL` / `0x10`):
![image](https://user-images.githubusercontent.com/1183985/97907779-a0328800-1cfa-11eb-9a85-6dbfc368d932.png)
(from section 9.15 of the datasheet, page 56)

As for why they're different, you'd have to ask ST however the values we're using are  as specified in the relevant section of the datasheets for the chips that we're using it for. Regardless of the labels that we're using, we're setting the register values as specified by the datasheet so you can rest assured that it's going to work as expected!
