### ISSUE TITLE
Temperature access 

### ISSUE THREAD

**Issue by Ninic0c0** [adafruit/Adafruit_CircuitPython_LSM6DS#34]
Hi :)

Could you please tell me if you plan to add temperature support for lsm6ds?
_LSM6DS_OUT_TEMP_L  is available but not use inside the lib

Cheers,

**Comment by caternuson** [comment]
Closing. There is already an issue open for this request here:
https://github.com/adafruit/Adafruit_CircuitPython_LSM6DS/issues/25
