### ISSUE TITLE
AttributeError: 'LSM6DSOX' object has no attribute '__class__'

### ISSUE THREAD

**Issue by Sawaiz** [adafruit/Adafruit_CircuitPython_LSM6DS#37]
The minimal example on 6.x below.

```python
import time
import board
import busio
from adafruit_lsm6ds.lsm6dsox import LSM6DSOX

i2c = busio.I2C(board.SCL, board.SDA)
sensor = LSM6DSOX(i2c)
```

Gives the error.

```python
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "adafruit_lsm6ds/lsm6dsox.py", line 22, in __init__
  File "adafruit_lsm6ds/__init__.py", line 208, in __init__
AttributeError: 'LSM6DSOX' object has no attribute '__class__'
```

I have the chip connected correctly since using direct I2C commands I can communicate with it and pull the device code. And changing the `SD0` pin changes its address.

```python
import board
import busio

i2c = busio.I2C(board.SCL, board.SDA)
while not i2c.try_lock():
    pass
print(i2c.scan())
i2c.unlock()
```

Yields

```python
main.py output:
[106]

Code done running.
```

There are two 10k pullups and pin one is in the top left corner of the image.
![PXL_20210226_131912426](https://user-images.githubusercontent.com/6422947/109305691-643da880-783e-11eb-993d-92ab4c9c5813.jpg)

Apologies for the horror.

**Comment by jposada202020** [comment]
Thanks :)
