### ISSUE TITLE
LSM6DSOX libraries issues @boot-up

### ISSUE THREAD

**Issue by TinManAkshay** [adafruit/Adafruit_CircuitPython_LSM6DS#43]
Hi,

I have installed these libraries using "sudo pip3 install adafruit-circuitpython-lsm6ds". I am using default python version is 3.7.4 on Pi 3B+.

I have LSM6DSOX with me and I can run (sudo python3 example_file_name.py) its example successfully and able to see the correct values on Raspbian OS.

However, my main python application is in /usr/bin/xxx.py and I want to integrate the code snippet from the example including libraries to my main .py file and run at boot-up. Its not recognizing these libraries for some reason. I cannot figure out why? Can someone please help me out here with the suggestions and solutions? I'd appreciate that.

Thanks,
Akshay

**Comment by ladyada** [comment]
hi this is more of a python question, good for forums/discord. not an issue with this library :)
