### ISSUE TITLE
Accelerometer rate frequency

### ISSUE THREAD

**Issue by exipilis** [adafruit/Adafruit_CircuitPython_LSM6DS#57]
https://github.com/adafruit/Adafruit_CircuitPython_LSM6DS/blob/main/adafruit_lsm6ds/__init__.py#L118

Probably you have meant
1666 instead of 1066.0
3332 instead of 3033.0
6664 instead of 6066.0
see sensor datasheet

**Comment by tekktrik** [comment]
According to the datasheet, it does look like these are currently incorrect and should be `1660.0`, `3330.0`, and `6660.0`.  Do you want to submit a PR to fix it?
